// app/layout.jsx

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/NavBar";
import SessionProviderWrapper from "./components/SessionProvider";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/util/auth";
import CartProvider from "./context/Cart";

// ✅ Add toastify import
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviderWrapper session={session}>
          <CartProvider>
            <Navbar />
            {children}

            <ToastContainer position="bottom-right" autoClose={2000} />
          </CartProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
