// app/layout.jsx (or .js)

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/NavBar";
import SessionProviderWrapper from "./components/SessionProvider";

import { getServerSession } from "next-auth/next";
import { authOptions } from "@/util/auth";
import CartProvider from "./context/Cart";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // Fetch session on server side
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviderWrapper session={session}>
          <CartProvider>
            <Navbar />
            {children}
          </CartProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
